export const dbData = {
  employees: [
    {
      employeeId: 1,
      firstName: "John",
      lastName: "Doe",
      position: "cook",
      rate: 10.5,
    },
    {
      employeeId: 2,
      firstName: "John",
      lastName: "Doe",
      position: "server",
      rate: 8.5,
    },
    {
      employeeId: 3,
      firstName: "John",
      lastName: "Doe",
      position: "sales manager",
      rate: 15.0,
    },
    {
      employeeId: 4,
      firstName: "John",
      lastName: "Doe",
      position: "front door clerk",
      rate: 8.5,
    },
  ],
  shifts: {
    monday: [
      {
        employeeId: 1,
        firstName: "John",
        lastName: "Doe",
        position: "cook",
        rate: 10.5,
      },
      {
        employeeId: 2,
        firstName: "John",
        lastName: "Doe",
        position: "server",
        rate: 8.5,
      },
      {
        employeeId: 3,
        firstName: "John",
        lastName: "Doe",
        position: "sales manager",
        rate: 15.0,
      },
      {
        employeeId: 4,
        firstName: "John",
        lastName: "Doe",
        position: "front door clerk",
        rate: 8.5,
      },
    ],
    tuesday: [
      {
        employeeId: 1,
        firstName: "John",
        lastName: "Doe",
        position: "cook",
        rate: 10.5,
      },
      {
        employeeId: 2,
        firstName: "John",
        lastName: "Doe",
        position: "server",
        rate: 8.5,
      },
      {
        employeeId: 3,
        firstName: "John",
        lastName: "Doe",
        position: "sales manager",
        rate: 15.0,
      },
      {
        employeeId: 4,
        firstName: "John",
        lastName: "Doe",
        position: "front door clerk",
        rate: 8.5,
      },
    ],
    wednesday: [
      {
        employeeId: 1,
        firstName: "John",
        lastName: "Doe",
        position: "cook",
        rate: 10.5,
      },
      {
        employeeId: 2,
        firstName: "John",
        lastName: "Doe",
        position: "server",
        rate: 8.5,
      },
      {
        employeeId: 3,
        firstName: "John",
        lastName: "Doe",
        position: "sales manager",
        rate: 15.0,
      },
      {
        employeeId: 4,
        firstName: "John",
        lastName: "Doe",
        position: "front door clerk",
        rate: 8.5,
      },
    ],
    thursday: [
      {
        employeeId: 1,
        firstName: "John",
        lastName: "Doe",
        position: "cook",
        rate: 10.5,
      },
      {
        employeeId: 2,
        firstName: "John",
        lastName: "Doe",
        position: "server",
        rate: 8.5,
      },
      {
        employeeId: 3,
        firstName: "John",
        lastName: "Doe",
        position: "sales manager",
        rate: 15.0,
      },
      {
        employeeId: 4,
        firstName: "John",
        lastName: "Doe",
        position: "front door clerk",
        rate: 8.5,
      },
    ],
    friday: [
      {
        employeeId: 1,
        firstName: "John",
        lastName: "Doe",
        position: "cook",
        rate: 10.5,
      },
      {
        employeeId: 2,
        firstName: "John",
        lastName: "Doe",
        position: "server",
        rate: 8.5,
      },
      {
        employeeId: 3,
        firstName: "John",
        lastName: "Doe",
        position: "sales manager",
        rate: 15.0,
      },
      {
        employeeId: 4,
        firstName: "John",
        lastName: "Doe",
        position: "front door clerk",
        rate: 8.5,
      },
    ],
    saturday: [
      {
        employeeId: 1,
        firstName: "John",
        lastName: "Doe",
        position: "cook",
        rate: 10.5,
      },
      {
        employeeId: 2,
        firstName: "John",
        lastName: "Doe",
        position: "server",
        rate: 8.5,
      },
      {
        employeeId: 3,
        firstName: "John",
        lastName: "Doe",
        position: "sales manager",
        rate: 15.0,
      },
      {
        employeeId: 4,
        firstName: "John",
        lastName: "Doe",
        position: "front door clerk",
        rate: 8.5,
      },
    ],
    sunday: [
      {
        employeeId: 1,
        firstName: "John",
        lastName: "Doe",
        position: "cook",
        rate: 10.5,
      },
      {
        employeeId: 2,
        firstName: "John",
        lastName: "Doe",
        position: "server",
        rate: 8.5,
      },
      {
        employeeId: 3,
        firstName: "John",
        lastName: "Doe",
        position: "sales manager",
        rate: 15.0,
      },
      {
        employeeId: 4,
        firstName: "John",
        lastName: "Doe",
        position: "front door clerk",
        rate: 8.5,
      },
    ],
  },
  users: [
    {
      id: 1,
      username: "asmith@generations.com",
      role: "USER",
    },
    {
      id: 2,
      username: "rjames@generations.com",
      role: "USER",
    },
    {
      id: 3,
      username: "bosslady@generations.com",
      role: "ADMIN",
    },
    {
      id: 4,
      username: "jdoe@generations.com",
      role: "USER",
    },
  ],
};
